[build]
  # Base directory - Netlify will operate from this folder
  base = "client"
  
  # Build command - no need to cd since we're already in client
  command = "npm install && npm run build"
  
  # Directory to publish - relative to base directory
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"
